# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' estimate the regression estimates based on given the number of repetitions
#'
#' @param x a Matrix
#' @param Y a Numeric Vector
#' @param Z a Numeric Vector for weight
#' @export
fastLmX_impl <- function(X, Y, Z) {
    .Call('_fast_fastLmX_impl', PACKAGE = 'fast', X, Y, Z)
}

